# Generated by Django 4.1.1 on 2022-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cota', models.CharField(max_length=10)),
                ('quantidade_cota', models.IntegerField()),
            ],
        ),
    ]
